name: flutterallwidgets
description: A new Flutter project.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  splashscreen:
  giffy_dialog:
  widget_with_codeview:
  webview_flutter:
  url_launcher:
  esys_flutter_share:
  firebase_admob: 
  firebase_messaging:
  cloud_firestore:
  in_app_purchase:
  firebase_core:
  

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/load.gif
   - lib/button/bropdownbutton.dart
   - lib/button/buttonnbar.dart
   - lib/button/flatbuttton.dart
   - lib/button/floatingactionbutt.dart
   - lib/button/iconbutton.dart
   - lib/button/popupmenubutton.dart
   - lib/button/raishedbutton.dart

   - lib/dialog/alertdialog.dart
   - lib/dialog/bottomsheet.dart
   - lib/dialog/customalert.dart
   - lib/dialog/expansionpannel.dart
   - lib/dialog/simmpledialog.dart
   - lib/dialog/snackbar.dart

   - lib/flutteranimation/anibuilder.dart
   - lib/flutteranimation/anicontainer.dart
   - lib/flutteranimation/anicrossfade.dart
   - lib/flutteranimation/anilalign.dart
   - lib/flutteranimation/anilistedstate.dart
   - lib/flutteranimation/animodebarrier.dart
   - lib/flutteranimation/aniopacity.dart
   - lib/flutteranimation/aniphysicalmotion.dart
   - lib/flutteranimation/anipositioned.dart
   - lib/flutteranimation/aniwidgetbasestate.dart
   - lib/flutteranimation/annodefaultstyle.dart
   - lib/flutteranimation/fadetrantion.dart
   - lib/flutteranimation/hero.dart
   - lib/flutteranimation/positionedtrantion.dart
   - lib/flutteranimation/rotaionaltransition.dart
   - lib/flutteranimation/scaletransition.dart
   - lib/flutteranimation/slidetrantion.dart

   - lib/fluttermultiplelayout/column.dart
   - lib/fluttermultiplelayout/custommultichildlayout.dart
   - lib/fluttermultiplelayout/flow.dart
   - lib/fluttermultiplelayout/gridview.dart
   - lib/fluttermultiplelayout/indexedstage.dart
   - lib/fluttermultiplelayout/layoutbuilder.dart
   - lib/fluttermultiplelayout/listbody.dart
   - lib/fluttermultiplelayout/listview.dart
   - lib/fluttermultiplelayout/rotaedbox.dart
   - lib/fluttermultiplelayout/row.dart
   - lib/fluttermultiplelayout/stack.dart
   - lib/fluttermultiplelayout/table.dart
   - lib/fluttermultiplelayout/transform.dart
   - lib/fluttermultiplelayout/wrap.dart
   
   - lib/fluttnavigatioo/flutterappbar.dart
   - lib/fluttnavigatioo/flutterbottomnavogation.dart
   - lib/fluttnavigatioo/flutterdrawer.dart
   - lib/fluttnavigatioo/fluttermaterialapp.dart
   - lib/fluttnavigatioo/flutterscaffold.dart
   - lib/fluttnavigatioo/flutterwidgetapp.dart
   - lib/fluttnavigatioo/flutttertabbarview.dart
   
   - lib/fscrolling/customscrollview.dart
   - lib/fscrolling/gridview.dart
   - lib/fscrolling/listview.dart
   - lib/fscrolling/nestedscrollview.dart
   - lib/fscrolling/notificationlistner.dart
   - lib/fscrolling/pageview.dart
   - lib/fscrolling/scrollable.dart
   - lib/fscrolling/scrollbar.dart
   - lib/fscrolling/scrollconfiguration.dart
   - lib/fscrolling/singlechildscrollview.dart

   - lib/painting&effect/backbropfilter.dart
   - lib/painting&effect/clipoval.dart
   - lib/painting&effect/clippath.dart
   - lib/painting&effect/cliprect.dart
   - lib/painting&effect/custompaint.dart
   - lib/painting&effect/decoratedbox.dart
   - lib/painting&effect/opacity.dart
   
   - lib/singlelayout/aspectrasio.dart
   - lib/singlelayout/baseline.dart
   - lib/singlelayout/center.dart
   - lib/singlelayout/constrainedbox.dart
   - lib/singlelayout/customsinglechildlayout.dart
   - lib/singlelayout/expanded.dart
   - lib/singlelayout/fittedbox.dart
   - lib/singlelayout/fractonallysizebox.dart
   - lib/singlelayout/intrinsicheight.dart
   - lib/singlelayout/intrinsicwrith.dart
   - lib/singlelayout/limitedbox.dart
   - lib/singlelayout/offstage.dart
   - lib/singlelayout/overflowbox.dart
   - lib/singlelayout/sizebox.dart

   

   

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
